---
title: "Research"
site: distill::distill_website
---
# Refereed Publications

### [Estimating Multidimensional Development Resilience](files/Estimating_Multidimensional_Development_Resilience.pdf){target="_blank"}

With [Kibrom A. Abay](https://www.ifpri.org/profile/kibrom-abay){target="_blank"}, [Christopher B. Barrett](http://barrett.dyson.cornell.edu/){target="_blank"} and [John H. Hoddinott](https://www.human.cornell.edu/people/jfh246){target="_blank"} - at *Journal of Development Economics* (January 2026)

 - Stata do-file generating multidimensional resilience measures [(link)](files/C&B_applications.do)

### [Food Security Dynamics in the U.S., 2001-2017](files/Food_Security_Dynamics_AJAE_published.pdf){target="_blank"} 

With [Christopher B. Barrett](http://barrett.dyson.cornell.edu/){target="_blank"} and [John H. Hoddinott](https://www.human.cornell.edu/people/jfh246){target="_blank"} - at *American Journal of Agricultural Economics* (October 2023)


<!-- ***Abstract***: We study household food security dynamics in the United States from 2001 to 2017 using a new measure, the probability of food security (PFS), the estimated probability that a household’s food expenditures equal or exceed the minimum cost of a healthful diet. We use PFS to analyze household-level and subpopulation-scale dynamics by investigating the conditional distribution of estimated food insecurity spells and the chronic and transient components of estimated food insecurity. We find that two-thirds of households experienced no estimated food insecurity during the 2001-17 period and more than half of newly food insecure households regain food security within two years. Households headed by female, non-White, or less educated individuals disproportionately suffer persistent, chronic and/or severe food insecurity.-->

# Working Papers

### [How much does SNAP Matter? SNAP’s Effects on Food Security](files/SNAP_on_Food_Security.pdf){target="_blank"}

### [The Probability of Food Security: A new longitudinal data set using the Panel Study of Income Dynamics](files/AEPP_4300-1_Manuscript_20250721_complete.pdf){target="_blank"}

With [John H. Hoddinott](https://www.human.cornell.edu/people/jfh246){target="_blank"}, [Christopher B. Barrett](http://barrett.dyson.cornell.edu/){target="_blank"}, and [Matthew P. Rabbitt](https://www.ers.usda.gov/authors/ers-staff-directory/matthew-p-rabbitt/){target="_blank"}  - *Revise and Resubmit* at *Applied Economic Perspectives & Policy*


# Work in Progress

<!--
### Poverty Dynamics in Peru - a Data-Driven Approach using Grouped Fixed Effects 

%With [Hongdi Zhao](https://hongdi-zhao.github.io/){target="_blank"}
-->

<!--
***Abstract***: Understanding individual and household-level welfare dynamics is very important, and it can help economics and policymakers to study and design policies to help households trapped in long-term poverty. However, long-term household-level panel data to study the poverty dynamics are often unavailable. The synthetic panel method has been used recently to estimate poverty transition using cross-sectional data, from bounded estimates under weaker assumptions to point estimates under stronger assumptions of cohort-level information. Point estimates have been very sensitive to how cohorts are defined, but there has been no clear guideline of how cohorts should be defined. This paper suggests a data-driven way to define cohorts, through clustering households with similar dynamics in the error term over the period into cohorts. Using the Peru National Household Survey on Living Conditions and Poverty (ENAHO) from 2007 to 2019, we estimate long-term poverty dynamics up to six years, testing the robustness of the estimates in the long run.
-->




<!--
***Abstract***: This study investigates the effects of SNAP on food security and its dynamics. The study uses state-level SNAP Policy Index as an exogenous variation as an instrumental variable for program benefit redemption. Using Panel Study of Income Dynamics (PSID) data, the study observe the effects of the program participation on food security over the next 10 years, using the measures of chronic and transitory food security constructed from the Probability of Food Security (PFS), a new food insecurity measure that reflects the estimated probability that the household’s predicted food expenditures exceed the cost of the Thrifty Food Plan (TFP) for its household composition, location and survey period.
-->

### Food Insecurity Among US Military Veterans

With [Senan Hogan-Hennessy](https://shoganhennessy.github.io/){target="_blank"}, [Christopher B. Barrett](http://barrett.dyson.cornell.edu/){target="_blank"}, [John H. Hoddinott](https://www.human.cornell.edu/people/jfh246){target="_blank"}, and [Matthew P. Rabbitt](https://www.ers.usda.gov/authors/ers-staff-directory/matthew-p-rabbitt/){target="_blank"}

### Inequality, Participation, and the Design of Local Development Projects: Experimental Evidence

with [Nathan Cook](https://nathancookphd.com/){target="_blank"}, [Tara Grillos](https://www.taragrillos.com/){target="_blank"}, and [Krister Andersson](https://keough.nd.edu/about/faculty-staff-directory/krister-andersson/){target="_blank"}

### Social Impact of Conservation Interventions

with [Sacha Ortiz Siani](https://keough.nd.edu/about/faculty-staff-directory/sacha-ortiz-siani/){target="_blank"}, [Krister Andersson](https://keough.nd.edu/about/faculty-staff-directory/krister-andersson/){target="_blank"}, [Lakshmi Iyer](https://sites.nd.edu/lakshmi-iyer/){target="_blank"} and [Daniel C. Miller](https://keough.nd.edu/about/faculty-staff-directory/daniel-miller/){target="_blank"}

<!--
### The Effects of REDD+ on Inequality

with [Nathan Cook](https://nathancookphd.com/){target="_blank"} and [Adriana Molina-Garzón](https://adrianamolinagarzon.com/){target="_blank"}
-->

### The Effects of Decentraliziation on Socioeconomic Well-being; Evidence from Bolivia and Peru

with [Valentina Muñoz Bernal](https://kellogg.nd.edu/valentina-mu%C3%B1oz-bernal){target="_blank"}, [Sacha Ortiz Siani](https://keough.nd.edu/about/faculty-staff-directory/sacha-ortiz-siani/){target="_blank"}, and [Krister Andersson](https://keough.nd.edu/about/faculty-staff-directory/krister-andersson/){target="_blank"}


# Other Publications

### [Domestic or Imported? An Analysis of Rice Demand in Senegal](files/Senegal_rice.pdf){target="_blank"}

With [Ndèye Fatou Faye](http://barrett.dyson.cornell.edu/staars/fellows/ndeye.html){target="_blank"}, [Amy Faye](http://barrett.dyson.cornell.edu/staars/fellows/amy.html){target="_blank"}, [Mouhamed Rassoul Sye](http://barrett.dyson.cornell.edu/staars/fellows/mouhamed.html){target="_blank"} and [John McPeak](https://jomcpeak.expressions.syr.edu/){target="_blank"}

<!-- ***Abstract***: Rice is among the most important cereals for African countries which absorb more than half of worldwide exports. West African countries depend particularly on rice imports in order to achieve food security. For this reason, many policy measures are implemented by governments to regulate the market and reduce the import dependency. This paper contributes to the rice policy debate by analyzing the demand side using the case study of Senegal in West Africa. We analyzed detailed data on rice consumption using a large primary survey of 6,328 rural and urban households in Senegal, with the QUAIDS model. Qualitative data were also collected and analyzed to better interpret results. We found that rural households consume far less local rice than their urban counterparts, meaning that location is a determinant of local rice consumption. We also show that types of rice consumed differ between rural and urban consumers. Urban households consume relatively more whole grain local rice while rural households consume more broken imported rice. Thus, to increase consumption of local rice, efforts should thus be made on the availability of broken local rice for both urban and rural consumers. Our results indicate no substitutability between domestic rice and imported rice in urban households and weak substitutability in rural households. In addition, results show that rice demand is price inelastic. Thus, price policies like subsidies or taxes may not be good shifters of domestic rice consumption. -->

